### ISSUE TITLE
Cannot build with Visual Studio 2017

### ISSUE THREAD

**Issue by Hemaolle** [NetHack/NetHack#545]
I'm not able to build with the latest version (15.9.36) of Visual Studio 2017 Community edition, even though https://github.com/NetHack/NetHack/blob/NetHack-3.7/sys/windows/Install.windows#L24 says this should be possible. This is the build output:

```
1>------ Build started: Project: uudecode, Configuration: Debug x64 ------
1>uudecode.c
1>d:\nethack\sys\share\uudecode.c(92): error C2143: syntax error: missing ')' before 'string'
1>d:\nethack\sys\share\uudecode.c(92): error C2143: syntax error: missing '{' before 'string'
1>d:\nethack\sys\share\uudecode.c(92): error C2059: syntax error: 'string'
1>d:\nethack\sys\share\uudecode.c(92): error C2059: syntax error: ')'
1>d:\nethack\sys\share\uudecode.c(180): error C2143: syntax error: missing ')' before 'string'
1>d:\nethack\sys\share\uudecode.c(180): error C2143: syntax error: missing '{' before 'string'
1>d:\nethack\sys\share\uudecode.c(180): error C2059: syntax error: 'string'
1>d:\nethack\sys\share\uudecode.c(180): error C2059: syntax error: ')'
1>Done building project "uudecode.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========
```

Building on Visual Studio 2019 works fine though, so perhaps it would be fine to just update the documentation to not claim Visual Studio 2017 support?

**Comment by nhmall** [comment]
Try changing line 67 in include/warnings.h from:
    #elif defined(_MSC_VER)
to:
#elif defined(_MSC_VER) && _MSC_VER > 1916

You'll likely get a bunch of noisy warnings, but it may build successfully.

``
--- a/include/warnings.h
+++ b/include/warnings.h
@@ -67,7 +67,7 @@
 #define RESTORE_WARNINGS _Pragma("GCC diagnostic pop")
 #define STDC_Pragma_AVAILABLE

-#elif defined(_MSC_VER)
+#elif defined(_MSC_VER) && _MSC_VER > 1916
 #define DISABLE_WARNING_UNREACHABLE_CODE \
                            _Pragma("warning( push )") \
                            _Pragma("warning( disable : 4702 )")

``

**Comment by Hemaolle** [comment]
The build indeed passes with that change 👍
