### ISSUE TITLE
Porting enquiry: Can SND_SOUNDEFFECTS_AUTOMAP be used without USER_SOUNDS?

### ISSUE THREAD

**Issue by JSI09** [NetHack/NetHack#1665]
NetHack 5.0.0, NetHack-5.0 branch.

Context. I'm building a mobile window port of NetHack 5.0 for iOS and Android, with its sound library registered through struct sound_procs. I want to use the NetHack 5.0 built-in sound effects, so I define SND_SOUNDEFFECTS_AUTOMAP. I can't use the user-supplied sounds feature as the mobile app has no user-editable config file. I leave USER_SOUNDS undefined.

Observation. In sounds.c, get_sound_effect_filename() sits inside SND_SOUNDEFFECTS_AUTOMAP block and reads sounddir to build the default path which I'm looking to use. However, sounddir is declared inside USER_SOUNDS block further up the file, and the only other reference (extern in cfgfiles.c) is also inside the USER_SOUNDS guard.

With SND_SOUNDEFFECTS_AUTOMAP defined + USER_SOUNDS undefined, get_sound_effect_filename() references an identifier that doesn't exist, and the file won't compile. Maybe this combination hasn't come up? since other ports using the automapping also enable user sounds.

Q: Is SND_SOUNDEFFECTS_AUTOMAP intended to work independently of USER_SOUNDS, or are they expected to be enabled together?
The effect-name mapping appears to serve the built-in effects rather than the user-sounds feature, and the two are separately gated elsewhere, so I just wanted to check the intention.

**Comment by nhmall** [comment]
> With SND_SOUNDEFFECTS_AUTOMAP defined + USER_SOUNDS undefined, get_sound_effect_filename() references an identifier that doesn't exist, and the file won't compile. Maybe this combination hasn't come up? since other ports using the automapping also enable user sounds.

A copy of the error message that was received would probably have been helpful.

I commented out USER_SOUNDS on a working platform in an attempt to try and reproduce an issue, and got this:
```
sounds.c
sounds.c(2006): error: 'sounddir': undeclared identifier
sounds.c(2006): warning: 'initializing': 'char *' differs in levels of indirection from 'int'
```

Moving the declaration of sounddir up a few lines so that it is not contained within the \#ifdef USER_SOUNDS block
should resolve that particular error, and a commit to do just that is now in the pipeline.  

```
diff --git a/src/sounds.c b/src/sounds.c
index 4fcd1c9de..999574562 100644
--- a/src/sounds.c
+++ b/src/sounds.c
@@ -1538,6 +1538,8 @@ tiphat(void)
     return res;
 }

+char *sounddir = 0; /* set in files.c */
+
 #ifdef USER_SOUNDS

 typedef struct audio_mapping_rec {
@@ -1551,7 +1553,6 @@ typedef struct audio_mapping_rec {
 static audio_mapping *soundmap = 0;
 static audio_mapping *sound_matches_message(const char *);

-char *sounddir = 0; /* set in files.c */

 /* adds a sound file mapping, returns 0 on failure, 1 on success */
 int

```

The particular combination of preprocessor definitions likely hadn't been tested prior to this, as you suggested.
Thanks for reporting this.

**Comment by nhmall** [comment]
Some platforms might still require a location from which to obtain sound effects, so further work is probably needed.

**Comment by JSI09** [comment]
Thank you for looking into this nhmall. I'll let you know if I come across anything as I get sound working. / J

**Comment by JSI09** [comment]
Thanks nhmall. On platforms still needing a location, a note on the mobile side, if it's useful.

'sff_default' resolves to 'sounddir/se_<name>.wav'. On iOS the assets live in the application bundle; on Android they're inside the APK, where they aren't filesystem objects and have to be reached through AssetManager. Neither has a path for sounddir unless the port first copies assets out to writable storage at first run.

I was planning to use 'sff_base_only' and resolve the base name myself against the bundle or the asset manager.
