### ISSUE TITLE
Building for Qt 5 fails

### ISSUE THREAD

**Issue by Meerkatdoken** [NetHack/NetHack#145]
Attempting to build using the linux-qt5 hint fails with:
`../win/Qt4/qt4main.cpp: In constructor ‘nethack_qt4::NetHackQtMainWindow::NetHackQtMainWindow(nethack_qt4::NetHackQtKeyBuffer&)’:
../win/Qt4/qt4main.cpp:612:5: error: invalid conversion from ‘int (*)(int)’ to ‘int (*)()’ [-fpermissive]`

I am attempting to build on Arch Linux with kernel 4.18.12, and Qt version 5.11.2.

**Comment by nhmall** [comment]
Fixed in ae61fe6f279654346250552ef9c6d866fe942cf8
